WebApplication/Controllers/CraveatsUserController.cs
using Generic.Obfuscation.TripleDES;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication.DAL;

namespace WebApplication.Controllers
{
    public class CraveatsUserController : Controller
    {
        private CraveatsDbContext db = new CraveatsDbContext();

        // GET: CraveatsUser
        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;


            Common.UserTypeEnum userTypeEnumFromSession = SessionManager.GetContextSessionOwnerType();

            int? sessionLoggedUserId = int.Parse(DataSecurityTripleDES.GetPlainText(
                SessionManager.GetContextSessionLoggedUserID()));

            var users = (userTypeEnumFromSession == Common.UserTypeEnum.CraveatsAdmin)
                ? from u in db.User
                  where u.Id != sessionLoggedUserId
                  select u
                : from u in db.User
                      where u.Id == 0
                      select u;

            if (!String.IsNullOrEmpty(searchString))
            {
                users = users.Where(s => ((s.FirstName?? "") + " " + (s.Surname??"")).Contains(searchString)
                                       || s.EmailAddress.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    users = users.OrderByDescending(s => ((s.FirstName ?? "") + " " + (s.Surname ?? "")));
                    break;
                case "Date":
                    users = users.OrderBy(s => s.LastUpdated);
                    break;
                case "date_desc":
                    users = users.OrderByDescending(s => s.LastUpdated);
                    break;
                default:  // Name ascending 
                    users = users.OrderBy(s => ((s.FirstName ?? "") + " " + (s.Surname ?? "")));
                    break;
            }

            int pageSize = 25;
            int pageNumber = (page ?? 1);
            return View(users.ToPagedList(pageNumber, pageSize));
        }

        //// GET: Restaurat/Details/xxx
        //public ActionResult Details(string id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }

        //    Restaurant Restaurant = db.Restaurant.Find(int.Parse(DataSecurityTripleDES.GetPlainText(id)));

        //    if (Restaurant == null)
        //    {
        //        return HttpNotFound();
        //    }

        //    return View(Restaurant);
        //}

        //// GET: Restaurant/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: Restaurant/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "Name, Detail, ContactNumber, EmailAddress")]Restaurant restaurant)
        //{
        //    try
        //    {
        //        if (ModelState.IsValid)
        //        {

        //            db.Restaurant.Add(restaurant);
        //            db.SaveChanges();

        //            restaurant.DateAdded = DateTime.Now;
        //            db.SaveChanges();

        //            restaurant.ServiceProviderStatus = (int?)Common.ServiceProviderStatusEnum.Inactive;
        //            restaurant.PartnerUserId = int.Parse(DataSecurityTripleDES.GetPlainText(SessionManager.GetContextSessionLoggedUserID()));
        //            restaurant.LastUpdated = DateTime.Now;
        //            db.SaveChanges();

        //            return RedirectToAction("AddAddress", "Profile", new
        //            {
        //                ownerType = DataSecurityTripleDES.GetEncryptedText((int)Common.OwnerTypeEnum.ServiceProvider),
        //                ownerId = DataSecurityTripleDES.GetEncryptedText(restaurant.Id)
        //            });
        //        }
        //    }
        //    catch (RetryLimitExceededException /* dex */)
        //    {
        //        //Log the error (uncomment dex variable name and add a line here to write a log.
        //        ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
        //    }
        //    return View(restaurant);
        //}

        //// GET: Restaurant/Edit/5
        //public ActionResult Edit(string id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Restaurant Restaurant = db.Restaurant.Find(int.Parse(DataSecurityTripleDES.GetPlainText(id)));
        //    if (Restaurant == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(Restaurant);
        //}

        //// POST: Restaurant/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost, ActionName("Edit")]
        //[ValidateAntiForgeryToken]
        //public ActionResult EditPost(string id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    var RestaurantToUpdate = db.Restaurant.Find(int.Parse(DataSecurityTripleDES.GetPlainText(id)));
        //    if (TryUpdateModel(RestaurantToUpdate, "",
        //       new string[] { "Name", "Detail", "ContactNumber", "EmailAddress" }))
        //    {
        //        try
        //        {
        //            db.SaveChanges();

        //            return RedirectToAction("Index");
        //        }
        //        catch (RetryLimitExceededException /* dex */)
        //        {
        //            //Log the error (uncomment dex variable name and add a line here to write a log.
        //            ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
        //        }
        //    }
        //    return View(RestaurantToUpdate);
        //}

        //// GET: Restaurant/Delete/5
        //public ActionResult Delete(string id, bool? saveChangesError = false)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    if (saveChangesError.GetValueOrDefault())
        //    {
        //        ViewBag.ErrorMessage = "Delete failed. Try again, and if the problem persists see your system administrator.";
        //    }
        //    Restaurant Restaurant = db.Restaurant.Find(int.Parse(DataSecurityTripleDES.GetPlainText(id)));
        //    if (Restaurant == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(Restaurant);
        //}

        //// POST: Restaurant/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(string id)
        //{
        //    try
        //    {
        //        Restaurant Restaurant = db.Restaurant.Find(int.Parse(DataSecurityTripleDES.GetPlainText(id)));
        //        db.Restaurant.Remove(Restaurant);
        //        db.SaveChanges();
        //    }
        //    catch (RetryLimitExceededException/* dex */)
        //    {
        //        //Log the error (uncomment dex variable name and add a line here to write a log.
        //        return RedirectToAction("Delete", new { id = id, saveChangesError = true });
        //    }
        //    return RedirectToAction("Index");
        //}
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication/Views/CraveatsUser/Index.cshtml
@model PagedList.IPagedList<WebApplication.DAL.User>
@using PagedList.Mvc;
@using Generic.Obfuscation.TripleDES;

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Restaurants</h2>

<div>
    <h4>Manage @ViewBag.AssetTypeName</h4>

    @*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@
    @using (Html.BeginForm("Index", "CraveatsUser", FormMethod.Get))
    {
        <p>
            Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
            <input type="submit" value="Search" />
        </p>
    }
    <table class="table">
        <tr>
            <th>
                @Html.ActionLink("FirstName", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("Surname", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                Detail
            </th>
            <th>
                @Html.ActionLink("Last Updated", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th></th>
        </tr>


        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Surname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EmailAddress)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastUpdated)
                </td>
                <td>
                    [
                    @*@Html.ActionLink("Details", "Details", new { id = DataSecurityTripleDES.GetEncryptedText(item.Id) }) |*@
                    @*@Html.ActionLink("Delete", "Delete", new { id = DataSecurityTripleDES.GetEncryptedText(item.Id) })*@
                    ]
                </td>
            </tr>
        }

    </table>
    <br />
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Index",
        new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}