WebApplication/Controllers/CartController.cs
using Generic.Obfuscation.TripleDES;
using Stripe;
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication.Common;
using WebApplication.DAL;
using WebApplication.Models;
using WebApplication.Models.ViewModel;

namespace WebApplication.Controllers
{
    [Authorize, Tls]
    public class CartController : Controller
    {
        private CraveatsDbContext db = new CraveatsDbContext();

        MenuModel menuModel = new MenuModel();

        // GET: Cart
        public ActionResult Index()
        {
            
            return View();
        }

        public ActionResult AddToCart(string id)
        {
            DAL.RestaurantMenu restaurantMenu = menuModel.find(int.Parse(DataSecurityTripleDES.GetPlainText(id)));
            RestaurantMenuCartDTO thisMenuDTO = EntityDTOHelper.GetEntityDTO<RestaurantMenu, RestaurantMenuCartDTO>(restaurantMenu);

            DAL.Restaurant restaurant = db.Restaurant.Find(restaurantMenu.OwnerId);

            thisMenuDTO.ServiceOwnerName = restaurant.Name;
            thisMenuDTO.ServiceOwnerId = DataSecurityTripleDES.GetEncryptedText(restaurant.Id);
            thisMenuDTO.ServiceOwnerType = DataSecurityTripleDES.GetEncryptedText((int)OwnerTypeEnum.ServiceProvider);

            DAL.Address address = db.Address.Find(restaurant.AddressId);
            if (address != null)
            {
                AddressDTO addressDTO = EntityDTOHelper.GetEntityDTO<DAL.Address, AddressDTO>(address);
                thisMenuDTO.ServiceOwnerAddressDetail = addressDTO.GetAddressString(true);
            }

            if (thisMenuDTO != null)
            {
                thisMenuDTO.Quantity = 1;

                CraveatsCart craveatsCart = (Session["cart"] == null) ? new CraveatsCart(SessionManager.GetContextSessionLoggedUserID()) : (Session["cart"] as CraveatsCart);
                craveatsCart.AddToCart(thisMenuDTO);

                Session["cart"] = craveatsCart;
            }

            return RedirectToAction("Index");
        }

        public ActionResult FinalisePayment(string stripeToken)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var cart = Session["cart"] as CraveatsCart;

                    

                    //long? total = (long)order.OrderTotal;
                    // Set your secret key: remember to change this to your live secret key in production
                    // See your keys here: https://dashboard.stripe.com/account/apikeys
                    StripeConfiguration.SetApiKey("sk_test_Rg2BSmdAQkVhLwSdOZyTqHGZ");

                    // Token is created using Checkout or Elements!
                    // Get the payment token submitted by the form:
                    //var token = CraveatsCart.Token; // Using ASP.NET MVC

                    long chargeAmount = (long)(decimal.Parse(CommonUtility.DoFormat((cart.CartTotalBeforeTax + cart.CartTotalTax))) * 100);
                    var options = new ChargeCreateOptions
                    {
                        Amount = chargeAmount,
                        Currency = "cad",
                        Description = "Order Payment 20181129",
                        SourceId = stripeToken
                    };
                    var service = new ChargeService();
                    Charge charge = service.Create(options);

                    if (charge.Status == "succeeded")
                    {
                        DAL.Order newOrder = new DAL.Order()
                        {
                            DateCreated = DateTime.Now,
                            DiscountTotal = 0.0m,
                            OrderStatus = (int)OrderStatusEnum.Paid,
                            OrderTotal = cart.CartTotalBeforeTax,
                            SessionId = int.Parse(DataSecurityTripleDES.GetPlainText(SessionManager.GetContextSessionID())),
                            TaxTotal = cart.CartTotalTax,
                            UserId = int.Parse(DataSecurityTripleDES.GetPlainText(cart.OwnerId))
                        };
                        db.Order.Add(newOrder);
                        db.SaveChanges();

                        foreach (RestaurantMenuCartDTO restaurantMenuCartDTO in cart.Items)
                        {
                            db.OrderDetail.Add(new OrderDetail()
                            {
                                IsTaxable = restaurantMenuCartDTO.IsTaxable,
                                OrderId = newOrder.Id,
                                ServiceId = int.Parse(DataSecurityTripleDES.GetPlainText(restaurantMenuCartDTO.Id)),
                                ServiceOwnerId = int.Parse(DataSecurityTripleDES.GetPlainText(restaurantMenuCartDTO.ServiceOwnerId)),
                                ServiceOwnerType = int.Parse(DataSecurityTripleDES.GetPlainText(restaurantMenuCartDTO.ServiceOwnerType)),
                                TaxRate = restaurantMenuCartDTO.TaxRate,
                                UnitPrice = restaurantMenuCartDTO.UnitPrice,
                                Quantity = restaurantMenuCartDTO.Quantity,
                                Name = restaurantMenuCartDTO.Name,
                                Detail = restaurantMenuCartDTO.Detail
                            });
                            db.SaveChanges();
                        }

                        db.OrderPayment.Add(new OrderPayment()
                        {
                            DateProcessed = DateTime.Now,
                            GatewayResponseCode = charge.Id,
                            GatewayResponseVerbose = charge.Status,
                            TotalAmount = (decimal)(charge.Amount / 100.00)
                        });
                        db.SaveChanges();

                        cart = null;
                        Session["cart"] = null;

                        return View("Success", new WebApplication.Models.ViewModel.OrderConfirmationDTO() {
                            Id = DataSecurityTripleDES.GetEncryptedText(newOrder.Id),
                            StatusMessage = "success"
                        });
                    }
                    else
                    {
                        ModelState.AddModelError("", "Unable to accept charges. Try again, and if the problem persists please review your card detail with your bank.");
                    }
                }
            }
            catch (RetryLimitExceededException /* dex */)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }
            return View();
        }

        public ActionResult Remove(string id)
        {
            RestaurantMenuCartDTO thisMenuDTO = EntityDTOHelper.GetEntityDTO<RestaurantMenu, RestaurantMenuCartDTO>(menuModel.find(int.Parse(DataSecurityTripleDES.GetPlainText(id))));
            if (thisMenuDTO != null && Session["cart"] != null)
            {
                CraveatsCart craveatsCart = Session["cart"] as CraveatsCart;
                craveatsCart.RemoveItem(id);

                Session["cart"] = craveatsCart;
            }

            return RedirectToAction("Index");
        }

        public ActionResult Success(OrderConfirmationDTO orderConfirmationDTO) {
            return View();
        }

    }
}

WebApplication/Controllers/HoldingPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication.Controllers
{
    public class HoldingPageController : Controller
    {
        // GET: HoldingPage
        public ActionResult Index()
        {
            return View(HoldingProfile());
        }

        // GET: HoldingPage/Profile
        public ActionResult HoldingProfile()
        {
            return View();
        }

        // GET: HoldingPage/Messages
        public ActionResult HoldingMessages()
        {
            return View();
        }

        // GET: HoldingPage/Orders
        public ActionResult HoldingOrders()
        {
            return View();
        }

        // GET: HoldingPage/Checkout
        public ActionResult HoldingCheckout()
        {
            return View();
        }
    }
}

WebApplication/Controllers/OrderHistoryController.cs
using Generic.Obfuscation.TripleDES;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication.DAL;
using WebApplication.Models.ViewModel;

namespace WebApplication.Controllers
{
    [Authorize, Tls]
    public class OrderHistoryController : Controller
    {
        private CraveatsDbContext db = new CraveatsDbContext();

        // GET: OrderHistory
        public ActionResult Index(string id)
        {
            var viewModel = new OrderOrderDetailIndexData();

            int userId = int.Parse(
                    DataSecurityTripleDES.GetPlainText(
                        SessionManager.GetContextSessionLoggedUserID()));

            List<Order> userOrders = db.Order.Where(u =>
                u.UserId == userId).OrderByDescending(
                    u => u.LastUpdated ?? u.DateCreated).ToList();

            List<OrderHistoryDTO> orderHistoryDTOs = new List<OrderHistoryDTO>();

            foreach (Order anOrder in userOrders)
            {
                orderHistoryDTOs.Add(EntityDTOHelper.GetEntityDTO<Order, OrderHistoryDTO>(anOrder));
            }
            viewModel.Orders = orderHistoryDTOs;

            if (id != null)
            {
                int? anOrderId = (int?)int.Parse(
                    DataSecurityTripleDES.GetPlainText(id));

                List<OrderDetail> userOrderDetails = db.OrderDetail.Where(u =>
                    u.OrderId == anOrderId).OrderBy(
                    u => u.Id).ToList();

                List<OrderDetailHistoryDTO> orderDetailHistoryDTO = new List<OrderDetailHistoryDTO>();
                foreach (OrderDetail anOrderDetail in userOrderDetails)
                {
                    orderDetailHistoryDTO.Add(EntityDTOHelper.GetEntityDTO<OrderDetail, OrderDetailHistoryDTO>(anOrderDetail));
                }

                ViewBag.OrderId = id;
                viewModel.OrderDetails = orderDetailHistoryDTO;
            }
            
            return View(viewModel);
        }
    }
}

WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="robots" content="noindex,nofollow"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Craveates - when you crave</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container" style="padding:0.3em 0em 0.3em 0em;">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*Html.ActionLink("Craveats", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
                <a href='@Url.Action("Index", "Home")' style="margin-top:5px;margin-bottom:5px;display:block;">
                    <img src='@Url.Content("~/Content/images/CraveatsNewText_215x65.png")' />
                </a>
            </div>
            <div class="navbar-collapse collapse sitebg" style="min-height:75px;height:75px;">
                <ul class="nav navbar-nav" style="margin-top:5px;margin-bottom:5px;">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                    <li>@Html.ActionLink("Profile", "ProfileView", "Profile")</li>
                    <li>@Html.ActionLink("Messages", "HoldingMessages", "HoldingPage")</li>
                    <li>@Html.ActionLink("Orders", "Index", "OrderHistory")</li>
                    <li>@Html.ActionLink("Checkout", "Index", "Cart")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content" style="margin-top:3em;">
        @RenderBody()
        <hr />
        <footer class="sitebg" style="padding-top:0.4em;padding-bottom:0.1em;">
            <p>&copy; @DateTime.Now.Year - Craveats - when you crave</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApplication/Views/Shared/_NoNavLayout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta name="robots" content="noindex,nofollow" />
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - Craveates - when you crave</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container" style="padding:0.3em 0em 0.3em 0em;">
                <div class="navbar-header sitebg" style="min-height:75px;height:75px;width:100%;">
                    <a href='javascript:void(0);' style="margin-top:5px;margin-bottom:5px;display:block;">
                        <img src='@Url.Content("~/Content/images/CraveatsNewText_215x65.png")' />
                    </a>
                </div>
            </div>
        </div>
        <div class="container body-content" style="margin-top:3em;">
            @RenderBody()
            <hr />
            <footer class="sitebg" style="padding-top:0.4em;padding-bottom:0.1em;">
                <p>&copy; @DateTime.Now.Year - Craveats - when you crave</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
</html>