WebApplication/Controllers/RestaurantMenuController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Generic.Obfuscation.TripleDES;
using PagedList;

using WebApplication.BLL;
using WebApplication.Common;
using WebApplication.DAL;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    [Authorize, Tls]
    public class RestaurantMenuController : Controller
    {
        private CraveatsDbContext db = new CraveatsDbContext();

        // GET: RestaurantMenu
        public ViewResult Index(

         string ownerType, string ownerId, 
         string sortOrder, string currentFilter, string searchString, int? page)
        {
            if (ownerType != null && ownerId != null)
            {
                ViewBag.ownerType = ownerType;
                ViewBag.ownerId = ownerId;
            }
            else
            {
                ownerType = DataSecurityTripleDES.GetEncryptedText((int) SessionManager.GetContextSessionOwnerType());
                ownerId = SessionManager.GetContextSessionLoggedUserID();

                ViewBag.ownerType = ownerType;
                ViewBag.ownerId = ownerId;
            }


            ViewBag.CurrentSort = sortOrder;

            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            int? filterId = int.Parse(DataSecurityTripleDES.GetPlainText(ownerId));
            var RestaurantMenus = SessionManager.GetContextSessionOwnerType() == UserTypeEnum.PartnerRestaurant 
                ? from s in db.RestaurantMenu 
                  where s.OwnerId == filterId && s.OwnerType == 2 && s.ServiceStatus == 1
                  select s
                : from s in db.RestaurantMenu
                  select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                RestaurantMenus = RestaurantMenus.Where(s => s.Name.Contains(searchString)
                                       || s.Detail.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    RestaurantMenus = RestaurantMenus.OrderByDescending(s => s.Name);
                    break;
                case "Date":
                    RestaurantMenus = RestaurantMenus.OrderBy(s => s.LastUpdated);
                    break;
                case "date_desc":
                    RestaurantMenus = RestaurantMenus.OrderByDescending(s => s.LastUpdated);
                    break;
                default:  // Name ascending 
                    RestaurantMenus = RestaurantMenus.OrderBy(s => s.Name);
                    break;
            }

            int pageSize = 25;
            int pageNumber = (page ?? 1);
            return View(RestaurantMenus.ToPagedList(pageNumber, pageSize));
        }

        // GET: RestaurantMenu/Create
        public ActionResult Create(string ownerType = null, string ownerId = null)
        {
            if (ownerType != null && ownerId != null)
            {
                ViewBag.ownerType = ownerType;
                ViewBag.ownerId = ownerId;
            }
            else
            {
                ownerType = DataSecurityTripleDES.GetEncryptedText((int)SessionManager.GetContextSessionOwnerType());
                ownerId = SessionManager.GetContextSessionLoggedUserID();

                ViewBag.ownerType = ownerType;
                ViewBag.ownerId = ownerId;
            }
            return View();
        }

        // POST: RestaurantMenu/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name, Brief, Detail, UnitPrice")]RestaurantMenu restaurantMenu, string ownerType = null, string ownerId = null)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    //int.Parse(DataSecurityTripleDES.GetPlainText(SessionManager.GetContextSessionLoggedUserID()));
                    db.RestaurantMenu.Add(restaurantMenu);
                    db.SaveChanges();

                    restaurantMenu.DateAdded = DateTime.Now;
                    db.SaveChanges();

                    restaurantMenu.ServiceStatus = (int?)Common.ServiceStatusEnum.Active;
                    restaurantMenu.OwnerId = int.Parse(
                        DataSecurityTripleDES.GetPlainText(
                            ownerId));
                    restaurantMenu.OwnerType = (int)Common.OwnerTypeEnum.ServiceProvider;
                    restaurantMenu.IsTaxable = true;
                    restaurantMenu.TaxRate = 13m;
                    restaurantMenu.LastUpdated = DateTime.Now;
                    db.SaveChanges();

                    Restaurant ownerRestaurant = db.Restaurant.FirstOrDefault(u => u.Id == restaurantMenu.OwnerId &&
                    (u.ServiceProviderStatus.HasValue &&
                    u.ServiceProviderStatus.Value == (int)Common.ServiceProviderStatusEnum.Inactive) &&
                    u.AddressId.HasValue);
                    if (ownerRestaurant != null)
                    {
                        ownerRestaurant.ServiceProviderStatus = (int)Common.ServiceProviderStatusEnum.Active;
                        db.SaveChanges();
                    }

                    return RedirectToAction("Index", new { ownerType = ownerType, ownerId = ownerId }); 
                }
            }
            catch (RetryLimitExceededException /* dex */)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }
            return View(restaurantMenu);
        }

        // GET: RestaurantMenu/Details/5
        public ActionResult Details(string id, string ownerType = null, string ownerId = null)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RestaurantMenu restaurantMenu = db.RestaurantMenu.Find(
                int.Parse(DataSecurityTripleDES.GetPlainText(id)));

            if (restaurantMenu == null)
            {
                return HttpNotFound();
            }

            return View(restaurantMenu);
        }

        // GET: RestaurantMenu/Edit/5
        public ActionResult Edit(string id, string ownerType = null, string ownerId = null)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RestaurantMenu restaurantMenu = db.RestaurantMenu.Find(int.Parse(DataSecurityTripleDES.GetPlainText(id)));
            if (restaurantMenu == null)
            {
                return HttpNotFound();
            }
            return View(restaurantMenu);
        }

        // POST: RestaurantMenu/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("EditMenu")]
        [ValidateAntiForgeryToken]
        public ActionResult EditPost([Bind(Include = "Name, Brief, Detail, UnitPrice")] RestaurantMenu restaurantMenu, 
            string id = null, 
            string ownerId = null, 
            string ownerType = null)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (restaurantMenu == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if ((restaurantMenu.Brief??string.Empty) == string.Empty || 
                (restaurantMenu.Name??string.Empty) == string.Empty || 
                (restaurantMenu.Detail??string.Empty) == string.Empty ||
                (restaurantMenu.UnitPrice ?? 0) <=  0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var RestaurantMenuToUpdate = db.RestaurantMenu.Find(int.Parse(DataSecurityTripleDES.GetPlainText(id)));
                        
            try
            {
                RestaurantMenuToUpdate.UnitPrice = restaurantMenu.UnitPrice;
                RestaurantMenuToUpdate.Name = restaurantMenu.Name;
                RestaurantMenuToUpdate.Detail = restaurantMenu.Detail;
                RestaurantMenuToUpdate.Brief = restaurantMenu.Brief;

                db.SaveChanges();

                return RedirectToAction("Index", new { ownerType = ownerType, ownerId = ownerId });
            }
            catch (RetryLimitExceededException /* dex */)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
            }

            return View(RestaurantMenuToUpdate);
        }

        // GET: RestaurantMenu/Delete/5
        public ActionResult Delete(string id, bool? saveChangesError = false, string ownerType = null, string ownerId = null)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (saveChangesError.GetValueOrDefault())
            {

WebApplication/Views/RestaurantMenu/Create.cshtml
@model WebApplication.DAL.RestaurantMenu

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "RestaurantMenu",
    new { ownerType = ViewBag.ownerType, ownerId = ViewBag.ownerId }, FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>Restaurant Menu</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Brief, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Brief, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Brief, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Detail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Detail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Detail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnitPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnitPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnitPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { ownerType = ViewBag.ownerType, ownerId = ViewBag.ownerId })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication/Views/RestaurantMenu/Delete.cshtml
@model WebApplication.DAL.RestaurantMenu
@using Generic.Obfuscation.TripleDES;

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RestaurantMenu</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Brief)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Brief)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Detail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Detail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnitPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitPrice)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.Hidden("ownerType", DataSecurityTripleDES.GetEncryptedText(Model.OwnerType))
        @Html.Hidden("ownerId", DataSecurityTripleDES.GetEncryptedText(Model.OwnerId))
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index", new { ownerType = DataSecurityTripleDES.GetEncryptedText(Model.OwnerType), ownerId = DataSecurityTripleDES.GetEncryptedText(Model.OwnerId) })
        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication/Views/RestaurantMenu/Details.cshtml
@model WebApplication.DAL.RestaurantMenu
@using Generic.Obfuscation.TripleDES;

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Restaurant Menu</h4>
    <hr />
    
    <input type="hidden" name="ownerType" value="@ViewBag.ownerType" />
    <input type="hidden" name="ownerId" value="@ViewBag.ownerId" />

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Brief)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Brief)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Detail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Detail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnitPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitPrice)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = DataSecurityTripleDES.GetEncryptedText(Model.Id), ownerType = ViewBag.ownerType, ownerId = ViewBag.ownerId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication/Views/RestaurantMenu/Edit.cshtml
@model WebApplication.DAL.RestaurantMenu
@using Generic.Obfuscation.TripleDES;

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm(actionName: "EditMenu", controllerName: "RestaurantMenu", method: FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>RestaurantMenu</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.Hidden("id", DataSecurityTripleDES.GetEncryptedText(Model.Id))
    @Html.Hidden("ownerType", DataSecurityTripleDES.GetEncryptedText(Model.OwnerType))
    @Html.Hidden("ownerId", DataSecurityTripleDES.GetEncryptedText(Model.OwnerId))


    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Brief, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Brief, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Brief, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Detail, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Detail, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Detail, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UnitPrice, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UnitPrice, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UnitPrice, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { ownerType = DataSecurityTripleDES.GetEncryptedText(Model.OwnerType), ownerId = DataSecurityTripleDES.GetEncryptedText(Model.OwnerId)})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication/Views/RestaurantMenu/Index.cshtml
@model PagedList.IPagedList<WebApplication.DAL.RestaurantMenu>
@using PagedList.Mvc;
@using Generic.Obfuscation.TripleDES;

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Restaurant Menus</h2>

<div>
    <h4>Manage @ViewBag.AssetTypeName</h4>

    <p>
        @Html.ActionLink("Create New", "Create", new { ownerType = ViewBag.ownerType, ownerId = ViewBag.ownerId })
    </p>
    @using (Html.BeginForm("Index", "RestaurantMenu", FormMethod.Get))
    {
        <input type="hidden" name="ownerType" value=@ViewBag.ownerType />
        <input type="hidden" name="ownerId" value=@ViewBag.ownerId />

        <p>
            Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
            <input type="submit" value="Search" />
        </p>
    }
    <table class="table">
        <tr>
            <th>
                @Html.ActionLink("Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                Detail
            </th>
            <th>
                @Html.ActionLink("Last Updated", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th></th>
        </tr>


        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Detail)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastUpdated)
                </td>
                <td>
                    [ @Html.ActionLink("View Restaurants", "Index", "Restaurant"/*, new {
                 id = DataSecurityTripleDES.GetEncryptedText(item.OwnerId)*//*,
                 ownerType = DataSecurityTripleDES.GetEncryptedText((int)WebApplication.Common.OwnerTypeEnum.ServiceProvider),
                 ownerId = DataSecurityTripleDES.GetEncryptedText(item.Id)*/ /*}, null*/) |
                    @Html.ActionLink("Edit", "Edit", new { id = DataSecurityTripleDES.GetEncryptedText(item.Id) }) |
                    @Html.ActionLink("Details", "Details", new { id = DataSecurityTripleDES.GetEncryptedText(item.Id) }) |
                    @Html.ActionLink("Delete", "Delete", new { id = DataSecurityTripleDES.GetEncryptedText(item.Id) }) ]
                </td>
            </tr>
        }

    </table>
    <br />
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Index",
        new { ownerType = ViewBag.ownerType, ownerId = ViewBag.ownerId, page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}